[enterjobedu_online]
title = "엔터잡에듀 ─ 온라인 클래스"
url = "https://www.enterjobedu.co.kr/online?page=1&&sort=new"
entrySelector = "div.lecture_list_wrap div.lecture_item"
titleSelector = "h4.lecture_item_title.ellipsis"
linkSelector = "a"
contentSelector = "span.lecture_item_lecture_item_tutors"
imageSelector = "img.thumbnail"
waitUntil = "networkidle"

[enterjobedu_offline]
title = "엔터잡에듀 ─ 오프라인 클래스"
url = "https://www.enterjobedu.co.kr/offline?page=1&&sort=new"
entrySelector = "div.lecture_list_wrap div.lecture_item"
titleSelector = "h4.lecture_item_title.ellipsis"
linkSelector = "a"
contentSelector = "span.lecture_item_lecture_item_tutors"
imageSelector = "img.thumbnail"
waitUntil = "networkidle"

[staccatoh_program]
title = "STACCATOH ─ Program"
url = "https://staccatoh.com/program/"
entrySelector = "ul.products.wpex-row.clr.match-height-grid li"
titleSelector = "h2.woocommerce-loop-product__title"
linkSelector = "a.woocommerce-LoopProduct-link.woocommerce-loop-product__link"
contentSelector = "p.product-subtitle"
imageSelector = "img.woo-entry-image-main"
waitUntil = "networkidle"

[eo_events]
title = "EO ─ 이벤트"
url = "https://events.eoeoeo.net/events"
entrySelector = "div.list-area div.row div.col-6.col-md-4"
titleSelector = "h5.card-title.mt-0.mb-1"
linkSelector = "div.mb-3 a"
contentSelector = "small.text-secondary.term.ml-2"
waitUntil = "networkidle"
