[enterjobedu_online]
title = "엔터잡에듀 ─ 온라인 클래스"
url = "https://www.enterjobedu.co.kr/online?page=1&&sort=new"
entrySelector = "div.lecture_list_wrap div.lecture_item"
titleSelector = "h4.lecture_item_title.ellipsis"
linkSelector = "a"
contentSelector = "span.lecture_item_lecture_item_tutors"
imageSelector = "img.thumbnail"
waitUntil = "networkidle"

[enterjobedu_offline]
title = "엔터잡에듀 ─ 오프라인 클래스"
url = "https://www.enterjobedu.co.kr/offline?page=1&&sort=new"
entrySelector = "div.lecture_list_wrap div.lecture_item"
titleSelector = "h4.lecture_item_title.ellipsis"
linkSelector = "a"
contentSelector = "span.lecture_item_lecture_item_tutors"
imageSelector = "img.thumbnail"
waitUntil = "networkidle"